# -*- coding: utf-8 -*-
"""CodeAlpha_Task3_Music_Generation_with_AI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dTyKJpSlFVqrlzEJTY2Cet0ycEkDr41Q

#Install_Music21
"""

!pip install music21
from music21 import corpus, note, chord, instrument, stream
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.utils import to_categorical

"""#MIDI_File_Load

"""

from music21 import corpus, note, chord

# MIDI file load
bach = corpus.parse('bwv66.6')

notes = []
for n in bach.flat.notes:
    if isinstance(n, note.Note):
        notes.append(str(n.pitch))
    elif isinstance(n, chord.Chord):
        notes.append('.'.join(str(pitch)for pitch in n.normalOrder))

print(f"Total notes: {len(notes)}")
print(notes[:10])

"""#Preprocessing+Sequencces"""

# Unique notes + mapping
unique_notes = sorted(list(set(notes)))
n_vocab = len(unique_notes)
note_to_int = dict((note, i) for i, note in enumerate(unique_notes))
int_to_note = dict((i, note) for i, note in enumerate(unique_notes))

# Sequences
seq_length = 100
input_seq = []
output_note = []

for i in range(len(notes) - seq_length):
    seq_in = notes[i:i + seq_length]
    seq_out = notes[i + seq_length]
    input_seq.append([note_to_int[note] for note in seq_in])
    output_note.append(note_to_int[seq_out])

n_patterns = len(input_seq)
X = np.reshape(input_seq, (n_patterns, seq_length, 1))
X = X / float(n_vocab)
y = to_categorical(output_note)

"""#LSTM_Model

"""

from keras.models import Sequential
from keras.layers import LSTM, Dense, Dropout
from keras.utils import to_categorical
import numpy as np

# Data reshape + normalize
X = np.reshape(input_seq, (len(input_seq), seq_length, 1))
X = X / float(n_vocab)
y = to_categorical(output_note)

model = Sequential()

model.add(
    LSTM(
        256,
        return_sequences=True,
        input_shape=(seq_length, 1)
        )
)

model.add(Dropout(0.3))

model.add(LSTM(256))

model.add(Dropout(0.3))

model.add(Dense(n_vocab, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam')

model.summary()

"""#Training_Test"""

# Training
print(f"Training on {len(X)} sequences...")
model.fit(X, y, epochs=50, batch_size=64, verbose=1)

model.save('music_lstm_model.h5')
print("Model saved as music_lstm_model.h5")

"""#Generate_Music"""

from music21 import instrument, note, chord, stream
import numpy as np

# notes generate
int_to_note = dict((i, note) for i, note in enumerate(unique_notes))

start = np.random.randint(0, len(input_seq)-1)
pattern = input_seq[start].copy()
prediction_output = []

def sample(preds, temperature=0.8):
    preds = np.asarray(preds).astype('float64')
    preds = np.log(preds + 1e-8) / temperature
    exp_preds = np.exp(preds)
    preds = exp_preds / np.sum(exp_preds)
    return np.random.choice(range(len(preds)), p=preds)

print("Generating 200 notes...")
for i in range(200):
    prediction_input = np.reshape(pattern, (1, seq_length, 1))
    prediction_input = prediction_input / float(n_vocab)

    prediction = model.predict(prediction_input, verbose=0)
    index = sample(prediction[0])

    result = int_to_note[index]
    prediction_output.append(result)

    pattern.append(index)
    pattern = pattern[1:len(pattern)]

print("Sample generated notes:", prediction_output[:20])

#MIDI code
offset = 0
output_notes = []
for pattern in prediction_output:
    if ('.' in pattern) or pattern.isdigit():
        notes_in_chord = pattern.split('.')
        notes = [note.Note(int(n)) for n in notes_in_chord]
        new_chord = chord.Chord(notes)
        new_chord.storedInstrument = instrument.Piano()
        output_notes.append(new_chord)
    # single note
    else:
        new_note = note.Note(pattern)
        new_note.offset = offset
        new_note.quarterLength = 0.5
        new_note.storedInstrument = instrument.Piano()

        output_notes.append(new_note)

        offset += 0.5

midi_stream = stream.Stream(output_notes)
midi_stream.write('midi', fp='generated_music.mid')
print("MIDI saved as generated_music.mid")

"""#Directly_Play"""

from google.colab import files
files.download('generated_music.mid')